### ISSUE TITLE
README/Documentation Enhancements

### ISSUE THREAD

**Issue by brandonfancher** [EOSIO/ricardian-template-toolkit#39]
README should document usage of the `rc` command line tool.
README should also document the various helpers/macros.

**Comment by josephjguerra** [comment]
* `rc` docs added in # [@v0.2.0](https://github.com/EOSIO/ricardian-template-toolkit/releases/tag/v0.2.0)
* helpers are documented in [ricardian-spec](https://github.com/EOSIO/ricardian-spec) as of [v0.2.0](https://github.com/EOSIO/ricardian-spec/releases/tag/v0.2.0)
